# Generated by Django 2.1 on 2018-08-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Piso')),
                ('number', models.CharField(max_length=10, verbose_name='Numero')),
                ('bedrooms', models.PositiveSmallIntegerField(verbose_name='Dormitorios')),
                ('bathrooms', models.PositiveSmallIntegerField(verbose_name='Baños')),
                ('totalSquareMeters', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Superficie')),
                ('usefulSquareMeters', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Superficie util')),
                ('orientation', models.CharField(choices=[('N', 'Norte'), ('NE', 'Norponiente'), ('E', 'Poniente'), ('SE', 'Surponiente'), ('S', 'Sur'), ('WS', 'Suroriente'), ('W', 'Oriente'), ('NW', 'Nororiente')], max_length=2, verbose_name='Orientacion')),
                ('generalDescription', models.CharField(default='', max_length=10000, verbose_name='Descripcion general')),
                ('tipoPropiedad', models.PositiveSmallIntegerField(choices=[(0, 'Usada'), (1, 'Nueva')], default=0, verbose_name='Tipo de propiedad')),
                ('antiguedad', models.PositiveSmallIntegerField(default=0, verbose_name='Antiguedad')),
                ('vidaUtil', models.PositiveSmallIntegerField(default=80, verbose_name='Vida util')),
                ('selloDeGases', models.PositiveSmallIntegerField(default=1, verbose_name='Sello de gases')),
                ('permisoEdificacionNo', models.PositiveSmallIntegerField(default=0, verbose_name='Numero permiso edificacion')),
                ('permisoEdificacionFecha', models.DateField(default='2006-10-25', verbose_name='Fecha permiso edificacion')),
                ('permisoEdificacionSuperficie', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Superficie permiso edificacion')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building', verbose_name='Edificio')),
            ],
        ),
    ]
