# Generated by Django 2.1 on 2019-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre'),
        ),
    ]
