# Generated by Django 2.1 on 2018-10-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='sourceId',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='sourceName',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='sourceUrl',
        ),
    ]
