# Generated by Django 2.1 on 2018-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20181017_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='terraceSquareMeters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie terraza'),
        ),
    ]
