# Generated by Django 2.1 on 2018-08-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '__first__'),
        ('apartment', '0003_auto_20180817_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio'),
        ),
    ]
