# Generated by Django 2.1 on 2018-10-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_terracesquaremeters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='marketPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado UF'),
        ),
    ]
