# Generated by Django 2.1 on 2018-08-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_apartment_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='neighborhood',
        ),
    ]
