# Generated by Django 2.1 on 2018-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_remove_apartment_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='generalDescription',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
    ]
