# Generated by Django 2.1 on 2018-11-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_auto_20181031_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='mercadoObjetivo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mercado objetivo'),
        ),
    ]
