# Generated by Django 2.1 on 2018-08-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_auto_20180827_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='generalDescription',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
    ]
