# Generated by Django 2.1 on 2018-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_auto_20180830_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='totalSquareMeters',
        ),
        migrations.AddField(
            model_name='apartment',
            name='builtSquareMeters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie construida'),
        ),
    ]
