# Generated by Django 2.1 on 2018-11-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_auto_20181101_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='builtSquareMeters',
        ),
    ]
