# Generated by Django 2.1 on 2018-09-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_auto_20180903_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='precioMercado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Precio mercado UF'),
        ),
    ]
