# Generated by Django 2.1 on 2018-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_remove_apartment_builtsquaremeters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='Dpto.'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='orientation',
            field=models.CharField(blank=True, choices=[('N', 'Norte'), ('NE', 'Norponiente'), ('E', 'Poniente'), ('SE', 'Surponiente'), ('S', 'Sur'), ('WS', 'Suroriente'), ('W', 'Oriente'), ('NW', 'Nororiente')], max_length=2, null=True, verbose_name='Orientación'),
        ),
    ]
