# Generated by Django 2.1 on 2018-09-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_apartment_preciomercado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='precioMercado',
            new_name='marketPrice',
        ),
        migrations.AddField(
            model_name='apartment',
            name='sourceId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source id'),
        ),
    ]
