# Generated by Django 2.1 on 2018-09-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_auto_20180903_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='Numero'),
        ),
    ]
