# Generated by Django 2.1 on 2018-11-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_auto_20181102_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dpto.'),
        ),
    ]
