# Generated by Django 2.1 on 2018-11-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_auto_20181113_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='number',
            new_name='addressNumber2',
        ),
    ]
