# Generated by Django 2.1 on 2018-09-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_auto_20180903_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Antiguedad'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='permisoEdificacionFecha',
            field=models.DateField(default='2006-10-25', null=True, verbose_name='Fecha permiso edificacion'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='permisoEdificacionNo',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Numero permiso edificacion'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='permisoEdificacionSuperficie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Superficie permiso edificacion'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='selloDeGases',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Sello de gases'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tipoPropiedad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Usada'), (1, 'Nueva')], default=0, null=True, verbose_name='Tipo de propiedad'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='vidaUtil',
            field=models.PositiveSmallIntegerField(default=80, null=True, verbose_name='Vida util'),
        ),
    ]
