# Generated by Django 2.1 on 2018-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_auto_20181115_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='addressNumber2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dpto.'),
        ),
    ]
