# Generated by Django 2.1 on 2018-09-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_auto_20180903_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='sourceName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
    ]
