# Generated by Django 2.1 on 2018-12-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_auto_20181119_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building_in',
            field=models.IntegerField(),
        ),
    ]
