# Generated by Django 2.1 on 2018-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0013_apartment_sourcename'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='sourceUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Source url'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sourceName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source name'),
        ),
    ]
