# Generated by Django 2.1 on 2018-12-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0014_auto_20181212_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentbuilding.ApartmentBuilding', verbose_name='Edificio'),
        ),
    ]
