# Generated by Django 2.1 on 2018-09-25 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('region', '0004_auto_20180824_1229'),
        ('commune', '0002_auto_20180824_1322'),
        ('apartment', '0014_auto_20180904_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='addressCommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='addressNumber',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='addressRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='addressStreet',
            field=models.CharField(default='', max_length=300, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio'),
        ),
    ]
