# Generated by Django 2.1 on 2018-09-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0016_apartment_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='addressNumber',
            field=models.CharField(default=0, max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[(0, 'Indefinido'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio')], default=0),
        ),
    ]
