# Generated by Django 2.1 on 2018-12-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0003_apartmentbuilding_building'),
        ('apartment', '0016_auto_20181218_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressNumber2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dpto.')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Piso')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dormitorios')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baños')),
                ('usefulSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie util')),
                ('terraceSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie terraza')),
                ('orientation', models.CharField(blank=True, choices=[('N', 'Norte'), ('NE', 'Norponiente'), ('E', 'Poniente'), ('SE', 'Surponiente'), ('S', 'Sur'), ('WS', 'Suroriente'), ('W', 'Oriente'), ('NW', 'Nororiente')], max_length=2, null=True, verbose_name='Orientación')),
                ('generalDescription', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general')),
                ('apartment_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartmentbuilding.ApartmentBuilding', verbose_name='Edificio')),
            ],
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='building_in',
            new_name='apartment_building',
        ),
    ]
