# Generated by Django 2.1 on 2018-12-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_auto_20181218_1845'),
        ('appraisal', '0051_auto_20181218_1828'),
        ('apartment', '0017_auto_20181218_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_building',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
