# Generated by Django 2.1 on 2018-12-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0003_apartmentbuilding_building'),
        ('apartment', '0018_auto_20181218_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment2',
            new_name='Apartment',
        ),
    ]
