# Generated by Django 2.1 on 2018-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0019_auto_20181218_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='estructuraTerminaciones',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Estructura y terminaciones'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='programa',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Programa'),
        ),
    ]
