# Generated by Django 2.1 on 2018-12-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0021_apartment_marketprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['addressNumber2']},
        ),
    ]
