# Generated by Django 2.1 on 2019-05-13 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('terrain', '__first__'),
        ('neighborhood', '0001_initial'),
        ('commune', '0001_initial'),
        ('condominium', '0001_initial'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre')),
                ('value', models.FloatField(blank=True, default=0, verbose_name='Valor en UF')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_UF', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio UF')),
                ('price_Peso', models.IntegerField(default=0, verbose_name='Precio Peso')),
                ('property_id', models.PositiveIntegerField()),
                ('property_type', models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (8, 'Terreno'), (26, 'Parcela eriaza'), (25, 'Parcela edificada'), (6, 'Oficina'), (19, 'Casa-Oficina'), (7, 'Local comercial'), (20, 'Propiedad comercial'), (9, 'Industria'), (11, 'Bodega'), (10, 'Galpon'), (21, 'Centro educacional'), (12, 'Estacionamiento'), (14, 'Barco'), (15, 'Vehículo'), (16, 'Maquinaria'), (17, 'Estación de servicio'), (18, 'Condominio'), (22, 'Hotel'), (23, 'Motel'), (24, 'Segunda vivienda'), (0, 'Otro')], default=0)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('price_Type', models.PositiveIntegerField(choices=[(1, 'Precio de Mercado'), (2, 'Precio de Tasación'), (3, 'Precio Conservador de Bienes Raíces'), (0, '----')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nombre')),
                ('addressStreet', models.CharField(blank=True, max_length=300, null=True, verbose_name='Calle')),
                ('addressNumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número')),
                ('addressFromCoords', models.BooleanField(default=False, verbose_name='Direccion por coordenadas')),
                ('lat', models.FloatField(default=0.0, verbose_name='Latitud')),
                ('lng', models.FloatField(default=0.0, verbose_name='Longitud')),
                ('sourceUrl', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Source url')),
                ('sourceName', models.CharField(blank=True, max_length=20, null=True, verbose_name='Source name')),
                ('sourceId', models.CharField(blank=True, max_length=20, null=True, verbose_name='Source id')),
                ('sourceDatePublished', models.DateTimeField(blank=True, null=True, verbose_name='Fecha publicación')),
                ('sourceAddedManually', models.BooleanField(blank=True, default=False, verbose_name='Añadido manualmente')),
                ('marketPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado UF')),
                ('addressCommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna')),
                ('addressCondominium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominium.Condominium', verbose_name='Condominio')),
                ('addressRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Región')),
                ('assets', models.ManyToManyField(to='realestate.Asset')),
                ('buildings', models.ManyToManyField(to='building.Building')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio')),
                ('terrains', models.ManyToManyField(to='terrain.Terrain')),
            ],
        ),
    ]
