<<<<<<< HEAD
# Generated by Django 2.1 on 2018-09-29 15:41
=======
# Generated by Django 2.1.1 on 2018-10-01 19:06
>>>>>>> a4fc519371f8ecea6e47821bd830a65770252142

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('commune', '0002_auto_20180824_1322'),
        ('region', '0004_auto_20180824_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyType', models.PositiveIntegerField(choices=[(0, 'Indefinido'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio')], default=0)),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.CharField(default=0, max_length=10, verbose_name='Numero')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nombre')),
                ('lat', models.FloatField(default=0.0, verbose_name='Latitud')),
                ('lng', models.FloatField(default=0.0, verbose_name='Longitud')),
                ('addressCommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna')),
                ('addressRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio')),
            ],
        ),
    ]
