# Generated by Django 2.1 on 2019-05-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal', verbose_name='Tasacion'),
        ),
    ]
