# Generated by Django 2.1 on 2019-01-30 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0016_auto_20190130_1641'),
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_UF', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio UF')),
                ('price_Peso', models.IntegerField(default=0, verbose_name='Precio Peso')),
                ('property_id', models.PositiveIntegerField()),
                ('property_type', models.PositiveIntegerField(choices=[('', '---------'), (8, 'Terreno'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (6, 'Oficina'), (7, 'Local Comercial'), (9, 'Industria'), (10, 'Galpon'), (11, 'Bodega'), (12, 'Estacionamiento'), (13, 'Parcela'), (14, 'Barco'), (15, 'Vehiculo'), (16, 'Maquinaria'), (17, 'Estación de Servicio'), (18, 'Condominio'), (0, 'Otro')], default=0)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('price_Type', models.PositiveIntegerField(choices=[(1, 'Precio de Mercado'), (2, 'Precio de Tasación'), (3, 'Precio Conservador de Bienes Raíces'), (0, '----')], default=0)),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal', verbose_name='Tasacion')),
            ],
        ),
    ]
