# Generated by Django 2.1 on 2018-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='sourceId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source id'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sourceName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source name'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sourceUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Source url'),
        ),
    ]
