# Generated by Django 2.1 on 2019-05-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
        ('realestate', '0002_price_appraisal'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='addressSquare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='square.Square', verbose_name='Manzana'),
        ),
    ]
