# Generated by Django 2.1 on 2018-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20181017_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='sourceDatePublished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha publicacion'),
        ),
    ]
