# Generated by Django 2.1 on 2018-10-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_auto_20181018_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='addressFromCoords',
            field=models.BooleanField(blank=True, null=True, verbose_name='Direccion por coordenadas'),
        ),
    ]
