# Generated by Django 2.1 on 2019-05-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '__first__'),
        ('realestate', '0003_auto_20190317_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio'),
        ),
    ]
