# Generated by Django 2.1 on 2019-05-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_realestate_addresssquare'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='addressSector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector'),
        ),
    ]
