# Generated by Django 2.1 on 2019-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_realestate_addresssector'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='addressSitio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sitio'),
        ),
    ]
