# Generated by Django 2.1 on 2018-10-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_realestate_addressfromcoords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='addressFromCoords',
            field=models.BooleanField(default=False, verbose_name='Direccion por coordenadas'),
        ),
    ]
