# Generated by Django 2.1 on 2019-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_realestate_addresssitio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='addressSector',
        ),
        migrations.AddField(
            model_name='realestate',
            name='addressLoteo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loteo'),
        ),
    ]
