# Generated by Django 2.1 on 2018-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_auto_20181018_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[(1, 'Casa'), (2, 'Departamento'), (3, 'Edificio'), (0, 'Otro')], default=0),
        ),
    ]
