# Generated by Django 2.1 on 2018-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20181023_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='acogidaLey',
            field=models.IntegerField(blank=True, choices=[(0, 'O.G.U. y C.'), (1, 'P.R.C.'), (2, 'Ley Pereira'), (3, 'Ley 19583'), (4, 'Ley 19667'), (5, 'Ley 19727'), (6, 'Ley 20251'), (7, 'Ley 6071'), (8, 'Ninguna'), (9, 'Antigüedad')], null=True, verbose_name='Acogida a'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='adobe',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Adobe'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='anoConstruccion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año construccion'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Antiguedad'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='avaluoFiscal',
            field=models.FloatField(blank=True, null=True, verbose_name='Avaluo fiscal'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='copropiedadInmobiliaria',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Copropiedad Inmobiliaria'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='desmontable',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Desmontable'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='destinoSII',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud')], max_length=1, null=True, verbose_name='Destino según SII'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='dfl2',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='DFL 2'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='expropiacion',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Expropiacion'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='marketPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado UF'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='mercadoObjetivo',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Mercado objetivo'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='ocupante',
            field=models.CharField(blank=True, choices=[('P', 'Propietario'), ('A', 'Arrendatario'), ('O', 'Otro'), ('SO', 'Sin ocupante')], max_length=2, null=True, verbose_name='Ocupante'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='permisoEdificacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Permiso edificación'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='permisoEdificacionDate',
            field=models.DateField(blank=True, null=True, verbose_name='Permiso edificación fecha'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='permisoEdificacionFecha',
            field=models.DateField(default='2006-10-25', null=True, verbose_name='Fecha permiso edificacion'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='permisoEdificacionNo',
            field=models.CharField(default=0, max_length=20, null=True, verbose_name='Numero permiso edificacion'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='permisoEdificacionSuperficie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Superficie permiso edificacion'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='recepcionFinal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Recepcion final'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='recepcionFinalDate',
            field=models.DateField(blank=True, null=True, verbose_name='Recepcion final fecha'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='selloVerde',
            field=models.CharField(blank=True, choices=[('V', 'Verde'), ('A', 'Amarillo'), ('R', 'Rojo'), ('NA', 'No Aplica'), ('VV', 'Verde vencido'), ('SA', 'Sin antecedentes')], max_length=2, null=True, verbose_name='Sello verde'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='tipoBien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de bien'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='tipoPropiedad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Usada'), (1, 'Nueva')], default=0, null=True, verbose_name='Tipo de propiedad'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='usoActual',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud')], max_length=1, null=True, verbose_name='Uso actual'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='usoFuturo',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud')], max_length=1, null=True, verbose_name='Uso futuro'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='vidaUtil',
            field=models.PositiveSmallIntegerField(default=80, null=True, verbose_name='Vida util'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='vidaUtilRemanente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida util remanente'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='viviendaSocial',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Vivienda social'),
        ),
    ]
