# Generated by Django 2.1 on 2018-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20181101_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='addressNumber',
            field=models.CharField(default=0, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='addressRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='anoConstruccion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año construcción'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='sourceDatePublished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha publicación'),
        ),
    ]
