# Generated by Django 2.1 on 2019-05-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_condominium_ctype'),
        ('realestate', '0007_remove_realestate_addresscondominium'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='addressCondominium',
            field=models.ManyToManyField(blank=True, to='condominium.Condominium', verbose_name='Condominio'),
        ),
    ]
