# Generated by Django 2.1 on 2018-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20181102_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('material', models.CharField(choices=[('-', 'Desconocido'), ('A', 'Acero'), ('B', 'Hormigón'), ('C', 'Albañilería'), ('D', 'Piedra/Bloque'), ('E', 'Madera'), ('F', 'Adobe'), ('G', 'Metalcom'), ('H', 'Prefab. Madera'), ('I', 'Prefab. Hormigón'), ('J', 'Otros')], default='-', max_length=2)),
                ('year', models.DateField(blank=True, null=True, verbose_name='Año construcción')),
                ('prenda', models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Mercado objetivo')),
                ('recepcion', models.IntegerField(choices=[(0, 'Con R/F'), (1, 'Sin R/F'), (2, 'Sin P/E'), (3, 'Sin Ant.'), (4, 'N/R')], default=4)),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Area')),
                ('ufPerArea', models.FloatField(blank=True, null=True, verbose_name='Area')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='constructions',
            field=models.ManyToManyField(to='realestate.Construction'),
        ),
    ]
