# Generated by Django 2.1 on 2018-11-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20181104_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='ufPerArea',
        ),
        migrations.AddField(
            model_name='construction',
            name='UFPerArea',
            field=models.FloatField(blank=True, default=0, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='area',
            field=models.FloatField(blank=True, default=0, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='year',
            field=models.DateField(blank=True, default='1985-01-01', verbose_name='Año construcción'),
        ),
    ]
