# Generated by Django 2.1 on 2018-11-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_auto_20181105_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='complementary',
            field=models.BooleanField(blank=True, default=False, verbose_name='Complementaria'),
        ),
    ]
