# Generated by Django 2.1 on 2018-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_construction_complementary'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='estructuraTerminaciones',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Estructura y terminaciones'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='programa',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Programa'),
        ),
    ]
