# Generated by Django 2.1 on 2018-11-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_auto_20181109_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='estructuraTerminaciones',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Estructura y terminaciones'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='programa',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Programa'),
        ),
    ]
