# Generated by Django 2.1 on 2018-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20181109_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='mercadoObjetivoTmp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Mercado objetivo'),
        ),
    ]
