# Generated by Django 2.1 on 2018-11-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_realestate_mercadoobjetivotmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='mercadoObjetivo',
        ),
    ]
