# Generated by Django 2.1 on 2018-11-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_remove_realestate_mercadoobjetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='mercadoObjetivoTmp',
            new_name='mercadoObjetivo',
        ),
    ]
