# Generated by Django 2.1 on 2018-11-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_auto_20181109_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='dfl2',
        ),
    ]
