# Generated by Django 2.1 on 2018-11-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_realestate_dfl2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='adobe',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='copropiedadInmobiliaria',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='desmontable',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='expropiacion',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='viviendaSocial',
        ),
    ]
