# Generated by Django 2.1 on 2018-11-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_auto_20181109_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='adobe',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='copropiedadInmobiliaria',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='desmontable',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='expropiacion',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='viviendaSocial',
        ),
    ]
