# Generated by Django 2.1 on 2018-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0022_auto_20181109_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='sourceUrl',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Source url'),
        ),
    ]
