# Generated by Django 2.1 on 2018-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_auto_20181113_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre')),
                ('area', models.FloatField(blank=True, default=0, verbose_name='Area')),
                ('UFPerArea', models.FloatField(blank=True, default=0, verbose_name='UF per Area')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='terrains',
            field=models.ManyToManyField(to='realestate.Terrain'),
        ),
    ]
