# Generated by Django 2.1 on 2018-11-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0026_auto_20181113_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre')),
                ('value', models.FloatField(blank=True, default=0, verbose_name='Valor en UF')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='assets',
            field=models.ManyToManyField(to='realestate.Asset'),
        ),
    ]
