# Generated by Django 2.1 on 2018-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0027_auto_20181113_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='sourceAddedManually',
            field=models.BooleanField(blank=True, default=False, verbose_name='Añadido manualmente'),
        ),
    ]
