# Generated by Django 2.1 on 2018-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0029_auto_20181115_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='quality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calidad'),
        ),
        migrations.AddField(
            model_name='construction',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin valor'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Muy bueno')], null=True, verbose_name='Estado'),
        ),
    ]
