# Generated by Django 2.1 on 2018-11-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0030_auto_20181115_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol'),
        ),
    ]
