# Generated by Django 2.1 on 2018-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0031_construction_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='shape',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Irregular')], null=True, verbose_name='Forma'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='topography',
            field=models.IntegerField(blank=True, choices=[(0, 'Plano'), (1, 'Semiplano'), (2, 'Pendiente'), (3, 'Pendiente abrupta')], null=True, verbose_name='Topografía'),
        ),
    ]
