# Generated by Django 2.1 on 2018-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0032_auto_20181115_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='permisoEdificacion',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='permisoEdificacionDate',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='permisoEdificacionFecha',
            field=models.DateField(default='2006-10-25', null=True, verbose_name='Fecha permiso edificación'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='permisoEdificacionNo',
            field=models.CharField(default=0, max_length=20, null=True, verbose_name='Permiso edificación'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='permisoEdificacionSuperficie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Superficie permiso edificación'),
        ),
    ]
