# Generated by Django 2.1 on 2018-11-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0033_auto_20181119_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='recepcionFinalDate',
            new_name='recepcionFinalFecha',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='recepcionFinal',
            new_name='recepcionFinalNo',
        ),
    ]
