# Generated by Django 2.1 on 2018-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0035_auto_20181120_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='material',
            field=models.CharField(blank=True, choices=[('-', 'Desconocido'), ('A', 'Acero'), ('B', 'Hormigón'), ('C', 'Albañilería'), ('D', 'Piedra/Bloque'), ('E', 'Madera'), ('F', 'Adobe'), ('G', 'Metalcom'), ('H', 'Prefab. Madera'), ('I', 'Prefab. Hormigón'), ('J', 'Otros')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='construction',
            name='recepcion',
            field=models.IntegerField(blank=True, choices=[(0, 'Con R/F'), (1, 'Sin R/F'), (2, 'Sin P/E'), (3, 'Sin Ant.'), (4, 'N/R')], default=4),
        ),
    ]
