# Generated by Django 2.1 on 2018-11-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0036_auto_20181120_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='addressNumber',
            field=models.CharField(blank=True, default=0, max_length=30, verbose_name='Número'),
        ),
    ]
