# Generated by Django 2.1 on 2018-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0037_auto_20181126_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio'), (0, 'Otro')], default=0),
        ),
    ]
