# Generated by Django 2.1 on 2018-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0038_auto_20181205_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='destinoSII',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud'), ('SE', 'Sitio Eriazo')], max_length=1, null=True, verbose_name='Destino según SII'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='recepcionFinalNo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Recepcion final'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='usoActual',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud'), ('SE', 'Sitio Eriazo')], max_length=1, null=True, verbose_name='Uso actual'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='usoFuturo',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud'), ('SE', 'Sitio Eriazo')], max_length=1, null=True, verbose_name='Uso futuro'),
        ),
    ]
