# Generated by Django 2.1 on 2018-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0040_auto_20181210_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio'), (4, 'Condominio'), (5, 'Terreno'), (0, 'Otro')], default=0),
        ),
    ]
