# Generated by Django 2.1 on 2018-12-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0043_remove_realestate_terrains'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Terrain',
        ),
    ]
