# Generated by Django 2.1 on 2018-12-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0001_initial'),
        ('realestate', '0044_delete_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='terrains',
            field=models.ManyToManyField(to='terrain.Terrain'),
        ),
    ]
