# Generated by Django 2.1 on 2018-12-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0045_realestate_terrains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='constructions',
        ),
    ]
