# Generated by Django 2.1 on 2018-12-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_building'),
        ('realestate', '0047_delete_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='buildings',
            field=models.ManyToManyField(to='building.Building'),
        ),
    ]
