# Generated by Django 2.1 on 2018-12-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0048_realestate_buildings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='acogidaLey',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='adobe',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='anoConstruccion',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='antiguedad',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='avaluoFiscal',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='copropiedadInmobiliaria',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='desmontable',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='destinoSII',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='dfl2',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='estructuraTerminaciones',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='expropiacion',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='mercadoObjetivo',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='ocupante',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='permisoEdificacionFecha',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='permisoEdificacionNo',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='permisoEdificacionSuperficie',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='recepcionFinalFecha',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='recepcionFinalNo',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='selloVerde',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='tipoBien',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='tipoPropiedad',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='usoActual',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='usoFuturo',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='vidaUtil',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='vidaUtilRemanente',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='viviendaSocial',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (2, 'Departamento'), (6, 'Oficina'), (7, 'Local Comercial'), (8, 'Terreno'), (9, 'Industria'), (10, 'Galpon'), (11, 'Bodega'), (12, 'Estacionamiento'), (3, 'Edificio'), (13, 'Parcela'), (14, 'Barco'), (15, 'Vehiculo'), (16, 'Maquinaria'), (17, 'Estación de Servicio'), (18, 'Condominio'), (0, 'Otro')], default=0),
        ),
    ]
