# Generated by Django 2.1 on 2018-12-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0049_auto_20181218_1828'),
    ]

    operations = [
    ]
