# Generated by Django 2.1 on 2018-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0050_auto_20181218_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='propertyType',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='addressNumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='addressStreet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Calle'),
        ),
    ]
