# Generated by Django 2.1 on 2019-05-13 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestate', '0001_initial'),
        ('apartment', '0001_initial'),
        ('house', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartmentbuilding', '0001_initial'),
        ('terrain', '__first__'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (8, 'Terreno'), (26, 'Parcela eriaza'), (25, 'Parcela edificada'), (6, 'Oficina'), (19, 'Casa-Oficina'), (7, 'Local comercial'), (20, 'Propiedad comercial'), (9, 'Industria'), (11, 'Bodega'), (10, 'Galpon'), (21, 'Centro educacional'), (12, 'Estacionamiento'), (14, 'Barco'), (15, 'Vehículo'), (16, 'Maquinaria'), (17, 'Estación de servicio'), (18, 'Condominio'), (22, 'Hotel'), (23, 'Motel'), (24, 'Segunda vivienda'), (0, 'Otro')], default=0)),
                ('property_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_main_type', models.IntegerField(choices=[('', '---------'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (8, 'Terreno'), (26, 'Parcela eriaza'), (25, 'Parcela edificada'), (6, 'Oficina'), (19, 'Casa-Oficina'), (7, 'Local comercial'), (20, 'Propiedad comercial'), (9, 'Industria'), (11, 'Bodega'), (10, 'Galpon'), (21, 'Centro educacional'), (12, 'Estacionamiento'), (14, 'Barco'), (15, 'Vehículo'), (16, 'Maquinaria'), (17, 'Estación de servicio'), (18, 'Condominio'), (22, 'Hotel'), (23, 'Motel'), (24, 'Segunda vivienda'), (0, 'Otro')], null=True, verbose_name='Estado')),
                ('timeCreated', models.DateTimeField(blank=True, null=True, verbose_name='Time created')),
                ('timeRequest', models.DateTimeField(blank=True, null=True, verbose_name='Time created')),
                ('timeDue', models.DateTimeField(blank=True, null=True, verbose_name='Time due')),
                ('timeModified', models.DateTimeField(blank=True, null=True, verbose_name='Time modified')),
                ('timeVisited', models.DateTimeField(blank=True, null=True, verbose_name='Time visited')),
                ('timeFinished', models.DateTimeField(blank=True, null=True, verbose_name='Time finished')),
                ('timePaused', models.DateTimeField(blank=True, null=True, verbose_name='Time paused')),
                ('state', models.IntegerField(choices=[(0, 'Importada'), (4, 'No asignada'), (5, 'No aceptada'), (1, 'Siendo tasada'), (6, 'En revisión'), (7, 'Enviada'), (8, 'Archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished'), (10, 'Devuelta')], null=True, verbose_name='Estado')),
                ('state_last', models.IntegerField(choices=[(0, 'Importada'), (4, 'No asignada'), (5, 'No aceptada'), (1, 'Siendo tasada'), (6, 'En revisión'), (7, 'Enviada'), (8, 'Archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished'), (10, 'Devuelta')], null=True, verbose_name='Estado')),
                ('in_conflict', models.BooleanField(default=False, verbose_name='En conflicto')),
                ('source', models.IntegerField(blank=True, choices=[(1, 'Tasación'), (2, 'Portal Inmbiliario'), (3, 'TocToc')], default=1, null=True, verbose_name='Fuente de tasación')),
                ('visita', models.IntegerField(blank=True, choices=[('', '---------'), (0, 'Sin Visita'), (1, 'Completa'), (2, 'Solo Exterior')], null=True, verbose_name='Visita')),
                ('tipoTasacion', models.IntegerField(blank=True, choices=[('', '---------'), (1, 'Hipotecaria'), (21, 'Convenio hipotecario'), (8, 'Garantía general'), (9, 'Pre-informe'), (11, 'Evaluación proyecto inmobiliario'), (12, 'Evaluación proyecto autoconstrucción'), (6, 'Avance de obra inmobiliario'), (10, 'Avance de obra autoconstrucción'), (20, 'Retasación garantía general'), (13, 'Final inmobiliaria'), (14, 'Final autoconstrucción'), (15, 'Remate'), (16, 'Agrícola'), (17, 'Vehículo'), (18, 'Máquinas y equipos'), (2, 'Revisión'), (19, 'Leasing'), (0, 'Otro')], null=True, verbose_name='Tipo Pedido')),
                ('finalidad', models.IntegerField(blank=True, choices=[('', '---------'), (2, 'Crédito'), (1, 'Garantía General'), (4, 'Venta Activos'), (6, 'Dación en Pago'), (3, 'Remate'), (5, 'Liquidación'), (7, 'Toma de Seguro'), (0, 'Otra')], null=True, verbose_name='Finalidad')),
                ('solicitante', models.IntegerField(blank=True, choices=[('', '---------'), (1, 'BCI'), (2, 'Santander'), (3, 'Itaú'), (4, 'Banco Internacional'), (5, 'Banco de Chile'), (6, 'Corpbanca'), (7, 'Scotiabank'), (8, 'BICE'), (0, 'Otro')], null=True, verbose_name='Solicitante')),
                ('solicitanteOtro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante')),
                ('solicitanteSucursal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante sucursal')),
                ('solicitanteCodigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante código')),
                ('solicitanteEjecutivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante ejecutivo')),
                ('solicitanteEjecutivoEmail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante email')),
                ('solicitanteEjecutivoTelefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Solicitante teléfono')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente')),
                ('clienteRut', models.CharField(blank=True, max_length=13, null=True, verbose_name='Cliente RUT')),
                ('clienteEmail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente Email')),
                ('clienteTelefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente Teléfono')),
                ('clienteValidado', models.BooleanField(blank=True, default=False, verbose_name='Cliente validado')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto')),
                ('contactoRut', models.CharField(blank=True, max_length=13, null=True, verbose_name='Contacto RUT')),
                ('contactoEmail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto Email')),
                ('contactoTelefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contacto Teléfono')),
                ('contactoValidado', models.BooleanField(blank=True, default=False, verbose_name='Cliente validado')),
                ('propietario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Propietario')),
                ('propietarioRut', models.CharField(blank=True, max_length=13, null=True, verbose_name='Propietario RUT')),
                ('propietarioEmail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto Email')),
                ('propietarioTelefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contacto Teléfono')),
                ('propietarioReferenceSII', models.BooleanField(blank=True, default=False, verbose_name='Propietario Referencia SII')),
                ('visadorEmpresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Visador empresa')),
                ('visadorEmpresaMail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Visador empresa mail')),
                ('orderFile', models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Documento pedido')),
                ('commentsOrder', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentarios pedido')),
                ('descripcionSector', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripción sector')),
                ('descripcionPlanoRegulador', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripción plano regulador')),
                ('descripcionExpropiacion', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripción expropiación')),
                ('valorUF', models.FloatField(blank=True, null=True, verbose_name='Valor UF')),
            ],
            options={
                'permissions': (('assign_tasador', 'Can assign tasadores'), ('assign_visador', 'Can assign visadores'), ('validate_contact', 'Can validate contacts'), ('change_time_due', 'Can change time due')),
            },
        ),
        migrations.CreateModel(
            name='AppraiserExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Descripcion del gasto')),
                ('totalPrice', models.IntegerField(default=0, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(1, 'Contacto validado'), (30, 'Contacto invalidado'), (9, 'Cliente validado'), (29, 'Cliente invalido'), (18, 'Anular tasación'), (23, 'Tasador solicitado'), (2, 'Solicitud de tasador aceptada'), (6, 'Solicitud de tasador rechazada'), (25, 'Tasador desasignado'), (26, 'Visador asignado'), (27, 'Visador desasignado'), (24, 'Tasación ingresada'), (3, 'Visita acordada'), (4, 'Propiedad visitada'), (5, 'Enviado a visador'), (31, 'Devuelta a tasador'), (32, 'Devuelta a visador'), (8, 'Entregado al cliente'), (10, 'Contabilización'), (19, 'Incidencia'), (20, 'Corrección informe'), (21, 'Observación visador'), (33, 'Reporte adjunto'), (28, 'Comentario'), (34, 'Tasación devuelta por cliente'), (0, 'Otro')], default=0)),
                ('text', models.CharField(max_length=500, verbose_name='Comment')),
                ('conflict', models.BooleanField(default=False, verbose_name='Incidencia')),
                ('timeCreated', models.DateTimeField(blank=True, null=True, verbose_name='Time created')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(default='no-img.jpg', upload_to='test/')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='no-img.jpg', null=True, upload_to='test/')),
                ('category', models.IntegerField(blank=True, choices=[('', '---------'), (0, 'Entorno'), (1, 'Emplazamiento'), (2, 'Fachada'), (3, 'Espacios comunes'), (4, 'Otra')], null=True, verbose_name='Categoría')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fixed', models.BooleanField(default=False, verbose_name='Fixed')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(null=True, upload_to='test/')),
                ('time_uploaded', models.DateTimeField(blank=True, null=True, verbose_name='Time uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'Sin datos'), (1, 'Definitivo'), (2, 'Matriz'), (3, 'En trámite'), (4, 'Preasignado'), (5, 'Bien común'), (6, 'Uso y Goce'), (7, 'No enrolado')], default=0, verbose_name='Estado')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apartment.Apartment')),
                ('apartment_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apartmentbuilding.ApartmentBuilding')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='house.House')),
                ('local_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='store.Store')),
                ('terrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='terrain.Terrain')),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalEvaluation',
            fields=[
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appraisal.Appraisal')),
                ('completeness', models.BooleanField(blank=True, default=True, verbose_name='Coordinacion en tiempo exigido')),
                ('generalQuality', models.BooleanField(blank=True, default=True, verbose_name='Visita en tiempo exigido')),
                ('onTime', models.BooleanField(blank=True, default=True, verbose_name='Despacho en tiempo exigido')),
                ('correctSurface', models.BooleanField(blank=True, default=True, verbose_name='Superficies correctas')),
                ('completeNormative', models.BooleanField(blank=True, default=True, verbose_name='Normativa completa y correcta')),
                ('homologatedReferences', models.BooleanField(blank=True, default=True, verbose_name='Contenidos resumidos adecuado')),
                ('commentText', models.CharField(blank=True, max_length=500, verbose_name='Comentarios de la tasación')),
                ('commentFeedback', models.CharField(blank=True, max_length=500, verbose_name='Feedback de la tasación')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appraisal.Appraisal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraiserexpenses',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='documents',
            field=models.ManyToManyField(to='appraisal.Document'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='photos',
            field=models.ManyToManyField(to='appraisal.Photo'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='property_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_main', to='appraisal.AppProperty'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='real_estate_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_main', to='realestate.RealEstate'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='real_estates',
            field=models.ManyToManyField(to='realestate.RealEstate'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='roles',
            field=models.ManyToManyField(to='appraisal.Rol'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='tasadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_tasador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='visadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_visador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appproperty',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
    ]
