# Generated by Django 2.1 on 2018-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('a', 'activa'), ('t', 'terminada')], default='a', max_length=10, verbose_name='Estado'),
        ),
    ]
