# Generated by Django 2.1.1 on 2018-09-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisal', '0001_initial'),
        ('realestate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='realEstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.RealEstate', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='tasadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_tasador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='visadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_visador', to=settings.AUTH_USER_MODEL),
        ),
    ]
