# Generated by Django 2.1 on 2019-01-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (0, 'Entorno'), (1, 'Emplazamiento'), (2, 'Fachada'), (3, 'Espacios comunes'), (4, 'Otra')], null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='no-img.jpg', null=True, upload_to='test/'),
        ),
    ]
