# Generated by Django 2.1 on 2018-10-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio tasación'),
        ),
    ]
