# Generated by Django 2.1 on 2018-08-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_appraisal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='timeCreated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time created'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='timeModified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time modified'),
        ),
    ]
