# Generated by Django 2.1 on 2019-01-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_auto_20190106_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='comments',
        ),
    ]
