# Generated by Django 2.1 on 2018-10-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_appraisal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='status',
            new_name='state',
        ),
    ]
