# Generated by Django 2.1 on 2019-01-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_remove_appraisal_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appraisal.Appraisal'),
        ),
    ]
