# Generated by Django 2.1 on 2018-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_auto_20180817_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='clienteRut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cliente RUT'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='propietario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='propietarioRut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Propietario RUT'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='rolAvaluo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rol avaluo'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante sucursal'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='solicitanteEjecutivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante ejecutivo'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='solicitanteSucursal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante sucursal'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='tasadorNombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tasador'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='tasadorRut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tasador rut'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='visadorEmpresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visador empresa'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='visadorEmpresaMail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visador empresa mail'),
        ),
    ]
