# Generated by Django 2.1 on 2018-10-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_comment_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='timePaused',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time paused'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='state',
            field=models.IntegerField(choices=[(1, 'active'), (3, 'finished'), (0, 'imported')], default=1, verbose_name='Estado'),
        ),
    ]
