# Generated by Django 2.1 on 2018-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_auto_20180817_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante'),
        ),
    ]
