# Generated by Django 2.1 on 2018-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_auto_20181012_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='state',
            field=models.IntegerField(choices=[(1, 'active'), (3, 'finished'), (2, 'paused'), (0, 'imported')], default=1, verbose_name='Estado'),
        ),
    ]
