# Generated by Django 2.1 on 2018-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_auto_20180827_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='valor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
