# Generated by Django 2.1 on 2019-01-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_photo_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='clienteTelefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente Teléfono'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='contactoTelefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contacto Teléfono'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='propietarioTelefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contacto Teléfono'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='solicitanteEjecutivoTelefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Solicitante teléfono'),
        ),
    ]
