# Generated by Django 2.1 on 2019-01-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_auto_20190112_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appproperty',
            name='property_type',
            field=models.PositiveIntegerField(choices=[('', '---------'), (8, 'Terreno'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (6, 'Oficina'), (7, 'Local Comercial'), (9, 'Industria'), (10, 'Galpon'), (11, 'Bodega'), (12, 'Estacionamiento'), (13, 'Parcela'), (14, 'Barco'), (15, 'Vehiculo'), (16, 'Maquinaria'), (17, 'Estación de Servicio'), (18, 'Condominio'), (0, 'Otro')], default=0),
        ),
    ]
