# Generated by Django 2.1 on 2018-08-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_appraisal_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='visadorEmpresaMail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Visador empresa mail'),
        ),
    ]
