# Generated by Django 2.1 on 2018-10-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_auto_20181017_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
