# Generated by Django 2.1 on 2019-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0007_auto_20190112_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='clienteValidado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cliente validado'),
        ),
    ]
