# Generated by Django 2.1 on 2018-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0007_auto_20180830_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='tasadorRut',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rut rut'),
        ),
    ]
