# Generated by Django 2.1 on 2018-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0007_auto_20181026_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='photo',
            field=models.ImageField(default='no-img.jpg', upload_to='.'),
        ),
    ]
