# Generated by Django 2.1 on 2018-09-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_auto_20180903_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='rolAvaluo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rol principal'),
        ),
    ]
