# Generated by Django 2.1 on 2018-10-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_auto_20181026_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='photo',
            field=models.ImageField(default='no-img.jpg', upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='solicitante',
            field=models.CharField(blank=True, choices=[('BCI', 'BCI'), ('SANTANDER', 'SANTANDER'), ('ITAÚ', 'ITAU'), ('INTERNACIONAL', 'BANCO INTERNACIONAL'), ('BANCO DE CHILE', 'BANCO DE CHILE'), ('CORPBANCA', 'CORPBANCA'), ('SOCTIABANK', 'SCOTIOABANK'), ('BICE', 'BICE'), (0, 'OTRO')], max_length=100, null=True, verbose_name='Solicitante'),
        ),
    ]
