# Generated by Django 2.1 on 2019-01-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_appraisal_clientevalidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='contactoValidado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cliente validado'),
        ),
    ]
