# Generated by Django 2.1 on 2018-09-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0009_auto_20180904_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='valor',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='valorUF',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor UF'),
        ),
    ]
