# Generated by Django 2.1 on 2018-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0009_auto_20181027_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='no-img.jpg', upload_to='test/')),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='photo',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='photos',
            field=models.ManyToManyField(to='appraisal.Photo'),
        ),
    ]
