# Generated by Django 2.1 on 2019-01-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0009_appraisal_contactovalidado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'permissions': (('assign_tasador', 'Can assign tasadores'), ('assign_visador', 'Can assign visadores'), ('validate_contact', 'Can validate contacts'))},
        ),
    ]
