# Generated by Django 2.1 on 2018-09-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0010_auto_20180904_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='tasadorNombre',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='tasadorRut',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='tasadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
