# Generated by Django 2.1 on 2018-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0010_auto_20181028_1458'),
    ]

    operations = [
    ]
