# Generated by Django 2.1 on 2018-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0011_appraisal_solicitantecodigo'),
    ]

    operations = [
    ]
