# Generated by Django 2.1 on 2018-09-13 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0012_auto_20180913_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='visadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_visador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='tasadorUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_tasador', to=settings.AUTH_USER_MODEL),
        ),
    ]
