# Generated by Django 2.1 on 2018-10-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0013_auto_20181028_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='clienteRut',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cliente RUT'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='solicitante',
            field=models.CharField(blank=True, choices=[(1, 'BCI'), (2, 'Santander'), (3, 'Itaú'), (4, 'Banco Internacional'), (5, 'Banco de Chile'), (6, 'Corpbanca'), (7, 'Scotiabank'), (8, 'BICE'), (0, 'Otro')], max_length=100, null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='source',
            field=models.IntegerField(blank=True, choices=[(1, 'Tasación'), (2, 'Portal Inmbiliario'), (3, 'TocToc')], default=1, null=True, verbose_name='Fuente de tasación'),
        ),
    ]
