# Generated by Django 2.1 on 2019-01-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
        ('appraisal', '0013_auto_20190123_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='real_estate_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_main', to='realestate.RealEstate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.IntegerField(choices=[(1, 'Contacto validado'), (30, 'Contacto invalidado'), (9, 'Cliente validado'), (29, 'Cliente invalido'), (23, 'Tasador solicitado'), (2, 'Solicitud de tasador aceptada'), (6, 'Solicitud de tasador rechazada'), (25, 'Tasador desasignado'), (26, 'Visador asignado'), (27, 'Visador desasignado'), (24, 'Tasación ingresada'), (3, 'Visita acordada'), (4, 'Propiedad visitada'), (5, 'Enviado a visador'), (8, 'Entregado al cliente'), (10, 'Contabilización'), (19, 'Incidencia'), (20, 'Corrección informe'), (21, 'Observación visador'), (28, 'Comentario'), (0, 'Otro')], default=0),
        ),
    ]
