# Generated by Django 2.1 on 2019-01-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0015_appraisal_property_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraiserExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Descripcion del gasto')),
                ('totalPrice', models.IntegerField(default=0, verbose_name='Precio')),
            ],
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='completeNormative',
            field=models.BooleanField(blank=True, default=True, verbose_name='Normativa completa y correcta'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='completeness',
            field=models.BooleanField(blank=True, default=True, verbose_name='Informe completo'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='correctSurface',
            field=models.BooleanField(blank=True, default=True, verbose_name='Superficies correctas'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='generalQuality',
            field=models.BooleanField(blank=True, default=True, verbose_name='Buena calidad general'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='homologatedReferences',
            field=models.BooleanField(blank=True, default=True, verbose_name='Referencias homologables'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='onTime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Entrega a tiempo'),
        ),
        migrations.AddField(
            model_name='appraiserexpenses',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
    ]
