# Generated by Django 2.1 on 2018-09-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='timeFinished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time finished'),
        ),
    ]
