# Generated by Django 2.1 on 2018-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0016_appraisal_timefinished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('f', 'finished')], default='a', max_length=10, verbose_name='Estado'),
        ),
    ]
