# Generated by Django 2.1 on 2019-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0016_auto_20190130_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='timeVisited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time visited'),
        ),
    ]
