# Generated by Django 2.1 on 2018-10-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0017_auto_20181030_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='rolAvaluo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol principal'),
        ),
    ]
