# Generated by Django 2.1 on 2019-01-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0017_auto_20190130_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='price',
        ),
    ]
