# Generated by Django 2.1 on 2018-09-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0018_auto_20180923_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'finished')], default=1, verbose_name='Estado'),
        ),
    ]
