# Generated by Django 2.1 on 2018-10-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0018_auto_20181030_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='objetivo',
            field=models.IntegerField(blank=True, choices=[(0, 'Otro'), (1, 'Garantía'), (2, 'Crédito'), (3, 'Remate'), (4, 'Venta'), (5, 'Liquidación')], null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='solicitanteCodigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante código'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='tipoTasacion',
            field=models.CharField(blank=True, choices=[(1, 'Hipotecaria'), (2, 'Revisión'), (3, 'Escritorio'), (4, 'Piloto'), (5, 'Terreno'), (0, 'Otra')], max_length=100, null=True, verbose_name='Tipo Pedido'),
        ),
    ]
