# Generated by Django 2.1 on 2018-10-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0019_auto_20181031_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='tipoTasacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Hipotecaria'), (2, 'Revisión'), (3, 'Escritorio'), (4, 'Piloto'), (5, 'Terreno'), (0, 'Otra')], max_length=100, null=True, verbose_name='Tipo Pedido'),
        ),
    ]
