# Generated by Django 2.1 on 2019-02-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0020_auto_20190130_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='state_last',
            field=models.IntegerField(choices=[(0, 'imported'), (4, 'not assigned'), (5, 'not accepted'), (1, 'in appraisal'), (6, 'in revision'), (7, 'sent'), (8, 'archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished')], null=True, verbose_name='Estado'),
        ),
    ]
