# Generated by Django 2.1 on 2019-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0021_appraisal_state_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='state',
            field=models.IntegerField(choices=[(0, 'Importada'), (4, 'No asignada'), (5, 'No aceptada'), (1, 'Siendo tasada'), (6, 'En revisión'), (7, 'Enviada'), (8, 'Archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished')], null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='state_last',
            field=models.IntegerField(choices=[(0, 'Importada'), (4, 'No asignada'), (5, 'No aceptada'), (1, 'Siendo tasada'), (6, 'En revisión'), (7, 'Enviada'), (8, 'Archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished')], null=True, verbose_name='Estado'),
        ),
    ]
