# Generated by Django 2.1 on 2018-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0021_auto_20181101_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='mercadoObjetivo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mercado objetivo'),
        ),
    ]
