# Generated by Django 2.1 on 2019-03-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0023_rol_local_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(null=True, upload_to='test/')),
                ('time_uploaded', models.DateTimeField(blank=True, null=True, verbose_name='Time uploaded')),
            ],
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='completeness',
            field=models.BooleanField(blank=True, default=True, verbose_name='Coordinacion en tiempo exigido'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='generalQuality',
            field=models.BooleanField(blank=True, default=True, verbose_name='Visita en tiempo exigido'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='homologatedReferences',
            field=models.BooleanField(blank=True, default=True, verbose_name='Contenidos resumidos adecuado'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='onTime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Despacho en tiempo exigido'),
        ),
    ]
