# Generated by Django 2.1 on 2018-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0023_remove_appraisal_mercadoobjetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='visita',
            field=models.IntegerField(blank=True, choices=[(0, 'Sin Visita'), (1, 'Completa'), (2, 'Solo Exterior')], null=True, verbose_name='Visita'),
        ),
    ]
