# Generated by Django 2.1 on 2019-03-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0024_auto_20190308_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='appraisal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
            preserve_default=False,
        ),
    ]
