# Generated by Django 2.1 on 2019-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0025_report_appraisal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='property_main_type',
            field=models.IntegerField(choices=[('', '---------'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (8, 'Terreno'), (26, 'Parcela eriaza'), (25, 'Parcela edificada'), (6, 'Oficina'), (19, 'Casa-Oficina'), (7, 'Local comercial'), (20, 'Propiedad comercial'), (9, 'Industria'), (11, 'Bodega'), (10, 'Galpon'), (21, 'Centro educacional'), (12, 'Estacionamiento'), (14, 'Barco'), (15, 'Vehículo'), (16, 'Maquinaria'), (17, 'Estación de servicio'), (18, 'Condominio'), (22, 'Hotel'), (23, 'Motel'), (24, 'Segunda vivienda'), (0, 'Otro')], null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='appproperty',
            name='property_type',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (8, 'Terreno'), (26, 'Parcela eriaza'), (25, 'Parcela edificada'), (6, 'Oficina'), (19, 'Casa-Oficina'), (7, 'Local comercial'), (20, 'Propiedad comercial'), (9, 'Industria'), (11, 'Bodega'), (10, 'Galpon'), (21, 'Centro educacional'), (12, 'Estacionamiento'), (14, 'Barco'), (15, 'Vehículo'), (16, 'Maquinaria'), (17, 'Estación de servicio'), (18, 'Condominio'), (22, 'Hotel'), (23, 'Motel'), (24, 'Segunda vivienda'), (0, 'Otro')], default=0),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='state',
            field=models.IntegerField(choices=[(0, 'Importada'), (4, 'No asignada'), (5, 'No aceptada'), (1, 'Siendo tasada'), (6, 'En revisión'), (7, 'Enviada'), (8, 'Archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished'), (10, 'Devuelta')], null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='state_last',
            field=models.IntegerField(choices=[(0, 'Importada'), (4, 'No asignada'), (5, 'No aceptada'), (1, 'Siendo tasada'), (6, 'En revisión'), (7, 'Enviada'), (8, 'Archivada'), (9, 'abortada'), (2, 'paused'), (3, 'finished'), (10, 'Devuelta')], null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='tipoTasacion',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (1, 'Hipotecaria'), (8, 'Garantía general'), (9, 'Pre-informe'), (11, 'Evaluación proyecto inmobiliario'), (12, 'Evaluación proyecto autoconstrucción'), (6, 'Avance de obra inmobiliario'), (10, 'Avance de obra autoconstrucción'), (13, 'Final inmobiliaria'), (14, 'Final autoconstrucción'), (15, 'Remate'), (16, 'Agrícola'), (17, 'Vehículo'), (18, 'Máquinas y equipos'), (2, 'Revisión'), (19, 'Leasing'), (0, 'Otro')], null=True, verbose_name='Tipo Pedido'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.IntegerField(choices=[(1, 'Contacto validado'), (30, 'Contacto invalidado'), (9, 'Cliente validado'), (29, 'Cliente invalido'), (23, 'Tasador solicitado'), (2, 'Solicitud de tasador aceptada'), (6, 'Solicitud de tasador rechazada'), (25, 'Tasador desasignado'), (26, 'Visador asignado'), (27, 'Visador desasignado'), (24, 'Tasación ingresada'), (3, 'Visita acordada'), (4, 'Propiedad visitada'), (5, 'Enviado a visador'), (31, 'Devuelta a tasador'), (32, 'Devuelta a visador'), (8, 'Entregado al cliente'), (10, 'Contabilización'), (19, 'Incidencia'), (20, 'Corrección informe'), (21, 'Observación visador'), (33, 'Reporte adjunto'), (28, 'Comentario'), (34, 'Tasación devuelta por cliente'), (0, 'Otro')], default=0),
        ),
    ]
