# Generated by Django 2.1 on 2019-03-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0026_auto_20190317_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'permissions': (('assign_tasador', 'Can assign tasadores'), ('assign_visador', 'Can assign visadores'), ('validate_contact', 'Can validate contacts'), ('change_time_due', 'Can change time due'))},
        ),
    ]
