# Generated by Django 2.1 on 2018-11-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0026_auto_20181102_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='propertyType',
        ),
    ]
