# Generated by Django 2.1 on 2018-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20181102_1123'),
        ('appraisal', '0027_remove_appraisal_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='valuationRealEstate',
            field=models.ManyToManyField(related_name='valuationRealEstate', to='realestate.RealEstate'),
        ),
    ]
