# Generated by Django 2.1 on 2018-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0029_auto_20181109_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='propietarioReferenceSII',
            field=models.BooleanField(blank=True, default=False, verbose_name='Propietario Referencia SII'),
        ),
    ]
