# Generated by Django 2.1 on 2018-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0030_appraisal_propietarioreferencesii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='valorUF',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor UF'),
        ),
    ]
