# Generated by Django 2.1 on 2018-11-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0031_auto_20181113_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onTime', models.IntegerField(blank=True, default=0, verbose_name='Puntualidad')),
                ('completeness', models.IntegerField(blank=True, default=0, verbose_name='Completitud')),
                ('generalQuality', models.IntegerField(blank=True, default=0, verbose_name='Calidad General')),
                ('commentText', models.CharField(blank=True, max_length=500, verbose_name='Comentarios de la tasación')),
                ('commentFeedback', models.CharField(blank=True, max_length=500, verbose_name='Feedback de la tasación')),
                ('appraisal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
