# Generated by Django 2.1 on 2018-11-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0032_appraisalevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(default='no-img.jpg', upload_to='test/')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.AddField(
            model_name='appraisal',
            name='documents',
            field=models.ManyToManyField(to='appraisal.Document'),
        ),
    ]
