# Generated by Django 2.1 on 2018-11-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0033_auto_20181118_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='appraisal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
    ]
