# Generated by Django 2.1 on 2018-11-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0034_auto_20181119_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='descripcionExpropiacion',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='descripcionPlanoRegulador',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='descripcionSector',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
    ]
