# Generated by Django 2.1.1 on 2018-11-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0034_auto_20181119_1418'),
        ('appraisal', '0031_merge_20181114_0957'),
    ]

    operations = [
    ]
