# Generated by Django 2.1.1 on 2018-11-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0035_auto_20181119_1548'),
        ('appraisal', '0035_merge_20181119_1633'),
    ]

    operations = [
    ]
