# Generated by Django 2.1 on 2018-11-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0036_auto_20181119_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='clienteRut',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Cliente RUT'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='propietarioRut',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Propietario RUT'),
        ),
    ]
