# Generated by Django 2.1.1 on 2018-11-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0036_merge_20181119_1650'),
        ('appraisal', '0037_auto_20181119_1858'),
    ]

    operations = [
    ]
