# Generated by Django 2.1 on 2018-11-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0038_auto_20181121_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
        migrations.AddField(
            model_name='appraisalevaluation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
