# Generated by Django 2.1 on 2018-11-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0039_auto_20181121_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='appraisalevaluation',
            name='id',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='clienteEmail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente Email'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='clienteTelefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cliente Teléfono'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='contactoEmail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto Email'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='contactoTelefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto Teléfono'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='finalidad',
            field=models.IntegerField(blank=True, choices=[(0, 'Otro'), (1, 'Garantía'), (2, 'Crédito'), (3, 'Remate'), (4, 'Venta'), (5, 'Liquidación')], null=True, verbose_name='Finalidad'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='solicitanteEjecutivoEmail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante email'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='solicitanteEjecutivoTelefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Solicitante teléfono'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='timeRequest',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time created'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='solicitanteOtro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appraisal.Appraisal'),
        ),
    ]
