# Generated by Django 2.1 on 2018-11-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0041_auto_20181126_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='appraisal',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='comments',
            field=models.ManyToManyField(to='appraisal.Comment'),
        ),
    ]
