# Generated by Django 2.1.1 on 2018-11-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0041_auto_20181126_1953'),
        ('appraisal', '0040_merge_20181121_1711'),
    ]

    operations = [
    ]
