# Generated by Django 2.1.1 on 2018-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0042_merge_20181127_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalevaluation',
            name='completeNormative',
            field=models.BooleanField(blank=True, default=True, verbose_name='Normativa Completa y correcta (5%)'),
        ),
        migrations.AddField(
            model_name='appraisalevaluation',
            name='correctSurface',
            field=models.BooleanField(blank=True, default=True, verbose_name='Superficies correctas -hasta un 5% de error- (15%)'),
        ),
        migrations.AddField(
            model_name='appraisalevaluation',
            name='homologatedReferences',
            field=models.BooleanField(blank=True, default=True, verbose_name='Referencias Homologables si las hubieran (2,5%)'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='completeness',
            field=models.BooleanField(blank=True, default=True, verbose_name='Aceptación del informe completo (50%)'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='generalQuality',
            field=models.BooleanField(blank=True, default=True, verbose_name='Calidad General -peso, imagenes claras configuración- (2,5%)'),
        ),
        migrations.AlterField(
            model_name='appraisalevaluation',
            name='onTime',
            field=models.BooleanField(blank=True, default=True, verbose_name='Entrega a tiempo (25%)'),
        ),
    ]
