# Generated by Django 2.1 on 2018-11-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0042_auto_20181127_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.IntegerField(choices=[(1, 'Contacto validado'), (2, 'Asignación aceptada'), (3, 'Acuerdo visita'), (4, 'Propiedad visitada'), (5, 'Informe enviado a UT'), (6, 'Informe validado a UT'), (7, 'Validación administrativa'), (8, 'Entregado al cliente'), (9, 'Cliente validado'), (10, 'Contabilización'), (11, 'Recepción física'), (12, 'Envío planilla para pago'), (13, 'Recepción facturación'), (14, 'Facturado'), (15, 'Pagado'), (16, 'Fondos disponibles'), (17, 'Cobranza'), (18, 'Abortado'), (19, 'Incidencia'), (20, 'Corección informe'), (21, 'Observación visador'), (22, 'Objeción'), (0, 'Otro')], default=0),
        ),
    ]
