# Generated by Django 2.1 on 2018-11-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0043_comment_event'),
        ('appraisal', '0043_auto_20181127_1159'),
    ]

    operations = [
    ]
