# Generated by Django 2.1 on 2018-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0044_merge_20181128_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='objetivo',
        ),
    ]
