# Generated by Django 2.1 on 2018-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0045_remove_appraisal_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='orderFile',
            field=models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Documento pedido'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='finalidad',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (0, 'Otro'), (1, 'Garantía'), (2, 'Crédito'), (3, 'Remate'), (4, 'Venta'), (5, 'Liquidación')], null=True, verbose_name='Finalidad'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='solicitante',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (1, 'BCI'), (2, 'Santander'), (3, 'Itaú'), (4, 'Banco Internacional'), (5, 'Banco de Chile'), (6, 'Corpbanca'), (7, 'Scotiabank'), (8, 'BICE'), (0, 'Otro')], null=True, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='state',
            field=models.IntegerField(choices=[(4, 'not assigned'), (1, 'active'), (3, 'finished'), (2, 'paused'), (0, 'imported')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='tipoTasacion',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (1, 'Hipotecaria'), (2, 'Revisión'), (3, 'Escritorio'), (4, 'Piloto'), (5, 'Terreno'), (0, 'Otra')], null=True, verbose_name='Tipo Pedido'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='visita',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (0, 'Sin Visita'), (1, 'Completa'), (2, 'Solo Exterior')], null=True, verbose_name='Visita'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.IntegerField(choices=[(1, 'Contacto validado'), (23, 'Asignado'), (24, 'Tasación ingresada'), (2, 'Asignación aceptada'), (3, 'Visita acordada'), (4, 'Propiedad visitada'), (5, 'Informe enviado a UT'), (6, 'Informe validado a UT'), (7, 'Validación administrativa'), (8, 'Entregado al cliente'), (9, 'Cliente validado'), (10, 'Contabilización'), (11, 'Recepción física'), (12, 'Envío planilla para pago'), (13, 'Recepción facturación'), (14, 'Facturado'), (15, 'Pagado'), (16, 'Fondos disponibles'), (17, 'Cobranza'), (18, 'Abortado'), (19, 'Incidencia'), (20, 'Corección informe'), (21, 'Observación visador'), (22, 'Objeción'), (0, 'Otro')], default=0),
        ),
    ]
