# Generated by Django 2.1 on 2018-12-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0046_auto_20181205_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='tipoTasacion',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (1, 'Hipotecaria'), (2, 'Revisión'), (3, 'Escritorio'), (4, 'Piloto'), (5, 'Terreno'), (6, 'Avance de obras'), (0, 'Otra')], null=True, verbose_name='Tipo Pedido'),
        ),
    ]
