# Generated by Django 2.1 on 2018-12-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0047_auto_20181210_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='realEstate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.RealEstate', verbose_name='Propiedad'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='tipoTasacion',
            field=models.IntegerField(blank=True, choices=[('', '---------'), (1, 'Hipotecaria'), (2, 'Revisión'), (3, 'Escritorio'), (4, 'Piloto'), (5, 'Terreno'), (6, 'Avance de obra'), (0, 'Otra')], null=True, verbose_name='Tipo Pedido'),
        ),
    ]
