# Generated by Django 2.1 on 2018-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0049_appraisal_commentsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.IntegerField(choices=[(1, 'Contacto validado'), (2, 'Asignación aceptada'), (9, 'Cliente validado'), (23, 'Asignado'), (24, 'Tasación ingresada'), (3, 'Visita acordada'), (4, 'Propiedad visitada'), (5, 'Enviado a visador'), (8, 'Entregado al cliente'), (10, 'Contabilización'), (18, 'Abortado'), (19, 'Incidencia'), (20, 'Corrección informe'), (21, 'Observación visador'), (22, 'Objeción'), (0, 'Otro')], default=0),
        ),
    ]
