# Generated by Django 2.1 on 2018-12-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0052_auto_20181220_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.PositiveIntegerField()),
                ('property_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='valuationRealEstate',
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='realEstate',
            field=models.ManyToManyField(to='realestate.RealEstate'),
        ),
        migrations.AddField(
            model_name='appproperty',
            name='appraisal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Appraisal'),
        ),
    ]
