# Generated by Django 2.1 on 2018-12-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0053_auto_20181220_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='realEstate',
            new_name='real_estates',
        ),
    ]
