# Generated by Django 2.1 on 2018-12-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0006_apartmentbuilding_addressnumber2'),
        ('apartment', '0022_auto_20181227_1654'),
        ('house', '0009_house_marketprice'),
        ('appraisal', '0054_auto_20181220_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apartment.Apartment'),
        ),
        migrations.AddField(
            model_name='rol',
            name='apartment_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apartmentbuilding.ApartmentBuilding'),
        ),
        migrations.AddField(
            model_name='rol',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='house.House'),
        ),
    ]
