# Generated by Django 2.1 on 2018-12-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0003_remove_terrain_rol'),
        ('appraisal', '0055_auto_20181227_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='terrain.Terrain'),
        ),
    ]
