# Generated by Django 2.1 on 2019-05-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commune', '__first__'),
        ('region', '__first__'),
        ('province', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True, verbose_name='Code')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.Province', to_field='code', verbose_name='Provincia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region')),
            ],
        ),
    ]
