# Generated by Django 2.1 on 2018-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Code'),
        ),
    ]
