# Generated by Django 2.1 on 2018-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0002_auto_20180827_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='code',
            field=models.BigIntegerField(unique=True, verbose_name='Code'),
        ),
    ]
