# Generated by Django 2.1 on 2018-08-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0003_auto_20180827_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='name',
        ),
    ]
