# Generated by Django 2.1 on 2018-08-24 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0003_auto_20180824_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Code')),
                ('mpoly', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region')),
            ],
        ),
    ]
