# Generated by Django 2.1 on 2018-11-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_regionsmall'),
        ('province', '0003_auto_20180824_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.RegionSmall', to_field='code', verbose_name='Region')),
            ],
        ),
    ]
