# Generated by Django 2.1 on 2019-05-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('iso', models.CharField(max_length=6, verbose_name='Iso')),
            ],
        ),
        migrations.CreateModel(
            name='RegionFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('iso', models.CharField(max_length=6, verbose_name='Iso')),
                ('dataApartmentCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Departamentos')),
                ('dataHouseCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Casas')),
                ('dataBuildingCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Edificios')),
            ],
        ),
    ]
