# Generated by Django 2.1 on 2018-08-24 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20180822_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
