# Generated by Django 2.1 on 2018-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_auto_20180824_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='dataApartmentCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Departamentos'),
        ),
        migrations.AddField(
            model_name='region',
            name='dataBuildingCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Edificios'),
        ),
        migrations.AddField(
            model_name='region',
            name='dataHouseCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Casas'),
        ),
    ]
