# Generated by Django 2.1 on 2018-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_auto_20181023_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('iso', models.CharField(max_length=6, verbose_name='Iso')),
            ],
        ),
    ]
