# Generated by Django 2.0.7 on 2018-08-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveSmallIntegerField(verbose_name='Dormitorios')),
                ('bathrooms', models.PositiveSmallIntegerField(verbose_name='Baños')),
                ('number', models.CharField(max_length=10, verbose_name='Numero')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Piso')),
                ('totalSquareMeters', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Superficie')),
                ('usefulSquareMeters', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Superficie util')),
                ('orientation', models.CharField(choices=[('N', 'Norte'), ('NE', 'Noreste'), ('E', 'Este'), ('SE', 'Sureste'), ('S', 'Sur'), ('WS', 'Suroeste'), ('W', 'Oeste'), ('NW', 'Noroeste')], max_length=2, verbose_name='Orientacion')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.PositiveSmallIntegerField(default=0, verbose_name='Numero')),
                ('addressCommune', models.CharField(default='', max_length=300, verbose_name='Comuna')),
                ('addressRegion', models.CharField(default='', max_length=300, verbose_name='Region')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Building', verbose_name='Edificio'),
        ),
    ]
