# Generated by Django 2.0.7 on 2018-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='building',
            name='lon',
            field=models.FloatField(default=0.0, verbose_name='Longitud'),
        ),
    ]
