# Generated by Django 2.1 on 2018-08-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180807_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
    ]
