# Generated by Django 2.1 on 2018-08-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_building_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.PositiveSmallIntegerField(default=0, verbose_name='Numero')),
                ('addressCommune', models.CharField(default='', max_length=300, verbose_name='Comuna')),
                ('addressRegion', models.CharField(default='', max_length=300, verbose_name='Region')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('lat', models.FloatField(default=0.0, verbose_name='Latitud')),
                ('lon', models.FloatField(default=0.0, verbose_name='Longitud')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='generalDescription',
            field=models.CharField(default='', max_length=10000, verbose_name='Descripcion general'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveSmallIntegerField(max_length=3, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='orientation',
            field=models.CharField(choices=[('N', 'Norte'), ('NE', 'Norponiente'), ('E', 'Poniente'), ('SE', 'Surponiente'), ('S', 'Sur'), ('WS', 'Suroriente'), ('W', 'Oriente'), ('NW', 'Nororiente')], max_length=2, verbose_name='Orientacion'),
        ),
    ]
