# Generated by Django 2.1 on 2018-08-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180808_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Antiguedad'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='permisoEdificacionFecha',
            field=models.DateField(default='2006-10-25', verbose_name='Fecha permiso edificacion'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='permisoEdificacionNo',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Numero permiso edificacion'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='permisoEdificacionSuperficie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Superficie permiso edificacion'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='selloDeGases',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Sello de gases'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tipoPropiedad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Usada'), (1, 'Nueva')], default=0, verbose_name='Tipo de propiedad'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='vidaUtil',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Vida util'),
        ),
    ]
