# Generated by Django 2.1 on 2018-08-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180808_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveSmallIntegerField(verbose_name='Piso'),
        ),
    ]
