# Generated by Django 2.1 on 2018-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Code'),
        ),
    ]
