# Generated by Django 2.1 on 2018-11-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0004_provincesmall'),
        ('region', '0006_regionsmall'),
        ('commune', '0003_auto_20181023_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.ProvinceSmall', to_field='code', verbose_name='Provincia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.RegionSmall', to_field='code', verbose_name='Region')),
            ],
        ),
    ]
