# Generated by Django 2.1 on 2018-11-02 15:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0004_communesmall'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('dataApartmentCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Departamentos')),
                ('dataHouseCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Casas')),
                ('dataBuildingCount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Edificios')),
            ],
        ),
        migrations.RemoveField(
            model_name='communesmall',
            name='province',
        ),
        migrations.RemoveField(
            model_name='communesmall',
            name='region',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='dataApartmentCount',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='dataBuildingCount',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='dataHouseCount',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='mpoly',
        ),
        migrations.DeleteModel(
            name='CommuneSmall',
        ),
    ]
