# Generated by Django 2.1 on 2018-11-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0005_auto_20181102_1240'),
        ('region', '0007_auto_20181102_1240'),
        ('province', '0005_auto_20181102_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='communefull',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='province.ProvinceFull', to_field='code', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='communefull',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.RegionFull', to_field='code', verbose_name='Region'),
        ),
    ]
