# Generated by Django 2.1 on 2019-05-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0006_auto_20181102_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='communefull',
            name='name_simple',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre simple'),
        ),
    ]
