# Generated by Django 2.1 on 2019-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0007_communefull_name_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='name_simple',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre simple'),
        ),
    ]
