# Generated by Django 2.1 on 2018-08-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='house',
            name='addressCommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='house',
            name='addressRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', verbose_name='Region'),
        ),
    ]
