# Generated by Django 2.1 on 2019-05-13 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='building',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Building', verbose_name='Edificio'),
        ),
    ]
