# Generated by Django 2.1 on 2018-10-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20181018_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='number',
        ),
        migrations.RemoveField(
            model_name='house',
            name='terraceSquareMeters',
        ),
        migrations.RemoveField(
            model_name='house',
            name='usefulSquareMeters',
        ),
        migrations.AddField(
            model_name='house',
            name='terrainSquareMeters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie terreno'),
        ),
    ]
