# Generated by Django 2.1 on 2018-12-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house2'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='old_id',
            field=models.IntegerField(null=True, verbose_name='tmp'),
        ),
    ]
