# Generated by Django 2.1 on 2018-08-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20180827_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='valorComercialUF',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Valor comercial UF'),
        ),
    ]
