# Generated by Django 2.1 on 2018-12-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='old_id',
        ),
        migrations.AddField(
            model_name='house2',
            name='old_id',
            field=models.IntegerField(null=True, verbose_name='tmp'),
        ),
    ]
