# Generated by Django 2.1.1 on 2018-10-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20181018_1225'),
        ('house', '0003_auto_20181024_1509'),
    ]

    operations = [
    ]
