# Generated by Django 2.1 on 2018-11-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20181101_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='builtSquareMeters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie construida'),
        ),
    ]
