# Generated by Django 2.1 on 2018-08-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_house_valorcomercialuf'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='areaUtilEdificacion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Metros cuadrados útiles construccion'),
        ),
        migrations.AddField(
            model_name='house',
            name='areaUtilTerreno',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Metros cuadrados útiles terreno'),
        ),
    ]
