# Generated by Django 2.1 on 2018-11-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_house_builtsquaremeters'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='addressNumber2',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Lote'),
        ),
    ]
