# Generated by Django 2.1.1 on 2018-11-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_house_builtsquaremeters'),
        ('house', '0005_auto_20181030_1701'),
    ]

    operations = [
    ]
