# Generated by Django 2.1 on 2018-12-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_auto_20181218_1845'),
        ('house', '0005_auto_20181218_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House2',
            new_name='House',
        ),
    ]
