# Generated by Django 2.1 on 2018-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20180827_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[(0, 'Indefinido'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio')], default=0),
        ),
    ]
