# Generated by Django 2.1 on 2018-12-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20181218_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='old_id',
        ),
    ]
