# Generated by Django 2.1 on 2018-09-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_house_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[(0, 'Indefinido'), (1, 'Casa'), (2, 'CHACALCA'), (3, 'Edificio')], default=0),
        ),
    ]
