# Generated by Django 2.1.1 on 2018-11-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_merge_20181119_1633'),
        ('house', '0007_auto_20181119_1904'),
    ]

    operations = [
    ]
