# Generated by Django 2.1 on 2018-09-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20180925_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[(0, 'Indefinido'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio')], default=0),
        ),
    ]
