# Generated by Django 2.1.1 on 2018-11-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_merge_20181121_1652'),
    ]

    operations = [

    ]
