# Generated by Django 2.1 on 2018-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.PositiveSmallIntegerField(default=0, verbose_name='Numero')),
                ('addressCommune', models.CharField(default='', max_length=300, verbose_name='Comuna')),
                ('addressRegion', models.CharField(default='', max_length=300, verbose_name='Region')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('lat', models.FloatField(default=0.0, verbose_name='Latitud')),
                ('lon', models.FloatField(default=0.0, verbose_name='Longitud')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
