# Generated by Django 2.1 on 2018-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='sourceName',
        ),
        migrations.RemoveField(
            model_name='building',
            name='sourceUrl',
        ),
        migrations.AddField(
            model_name='building',
            name='fromApartment',
            field=models.BooleanField(default=False, verbose_name='Creado desde departamento'),
        ),
    ]
