# Generated by Django 2.1 on 2019-01-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20190105_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='rol',
        ),
        migrations.AlterField(
            model_name='building',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Año construcción'),
        ),
    ]
