# Generated by Django 2.1 on 2018-08-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20180817_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appraisal',
        ),
    ]
