# Generated by Django 2.1 on 2019-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_auto_20190106_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (8, 'Terreno'), (26, 'Parcela eriaza'), (25, 'Parcela edificada'), (6, 'Oficina'), (19, 'Casa-Oficina'), (7, 'Local comercial'), (20, 'Propiedad comercial'), (9, 'Industria'), (11, 'Bodega'), (10, 'Galpon'), (21, 'Centro educacional'), (12, 'Estacionamiento'), (14, 'Barco'), (15, 'Vehículo'), (16, 'Maquinaria'), (17, 'Estación de servicio'), (18, 'Condominio'), (22, 'Hotel'), (23, 'Motel'), (24, 'Segunda vivienda'), (0, 'Otro')], default=0),
        ),
    ]
