# Generated by Django 2.1 on 2018-08-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('building', '0003_delete_appraisal'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Barrio'),
        ),
    ]
