# Generated by Django 2.1 on 2018-08-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_building_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='addressCommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='building',
            name='addressRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', verbose_name='Region'),
        ),
    ]
