# Generated by Django 2.1 on 2018-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_auto_20181101_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='acogidaLey',
            field=models.IntegerField(blank=True, choices=[(0, 'O.G.U. y C.'), (1, 'P.R.C.'), (2, 'Ley Pereira'), (3, 'Ley 19583'), (4, 'Ley 19667'), (5, 'Ley 19727'), (6, 'Ley 20251'), (7, 'Ley 6071'), (8, 'Ninguna'), (9, 'Antigüedad')], null=True, verbose_name='Adobe'),
        ),
        migrations.AddField(
            model_name='building',
            name='adobe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Adobe'),
        ),
        migrations.AddField(
            model_name='building',
            name='desmontable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Desmontable'),
        ),
    ]
