# Generated by Django 2.1 on 2018-11-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_auto_20181101_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='adobe',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Adobe'),
        ),
    ]
