# Generated by Django 2.1 on 2018-08-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_auto_20180827_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='addressCommune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='building',
            name='addressRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region'),
        ),
    ]
