# Generated by Django 2.1 on 2018-11-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_auto_20181101_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='copropiedadInmobiliaria',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Copropiedad Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='building',
            name='desmontable',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Desmontable'),
        ),
        migrations.AlterField(
            model_name='building',
            name='dfl2',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='DFL 2'),
        ),
        migrations.AlterField(
            model_name='building',
            name='expropiacion',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Expropiacion'),
        ),
        migrations.AlterField(
            model_name='building',
            name='viviendaSocial',
            field=models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Vivienda social'),
        ),
    ]
