# Generated by Django 2.1 on 2018-09-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_auto_20180827_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
