# Generated by Django 2.1 on 2018-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_auto_20180903_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sourceName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source'),
        ),
    ]
