# Generated by Django 2.1 on 2018-11-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_auto_20181101_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='acogidaLey',
        ),
        migrations.RemoveField(
            model_name='building',
            name='adobe',
        ),
        migrations.RemoveField(
            model_name='building',
            name='anoConstruccion',
        ),
        migrations.RemoveField(
            model_name='building',
            name='avaluoFiscal',
        ),
        migrations.RemoveField(
            model_name='building',
            name='copropiedadInmobiliaria',
        ),
        migrations.RemoveField(
            model_name='building',
            name='desmontable',
        ),
        migrations.RemoveField(
            model_name='building',
            name='destinoSII',
        ),
        migrations.RemoveField(
            model_name='building',
            name='dfl2',
        ),
        migrations.RemoveField(
            model_name='building',
            name='expropiacion',
        ),
        migrations.RemoveField(
            model_name='building',
            name='ocupante',
        ),
        migrations.RemoveField(
            model_name='building',
            name='permisoEdificacion',
        ),
        migrations.RemoveField(
            model_name='building',
            name='permisoEdificacionDate',
        ),
        migrations.RemoveField(
            model_name='building',
            name='recepcionFinal',
        ),
        migrations.RemoveField(
            model_name='building',
            name='recepcionFinalDate',
        ),
        migrations.RemoveField(
            model_name='building',
            name='selloVerde',
        ),
        migrations.RemoveField(
            model_name='building',
            name='tipoBien',
        ),
        migrations.RemoveField(
            model_name='building',
            name='usoActual',
        ),
        migrations.RemoveField(
            model_name='building',
            name='usoFuturo',
        ),
        migrations.RemoveField(
            model_name='building',
            name='vidaUtilRemanente',
        ),
        migrations.RemoveField(
            model_name='building',
            name='viviendaSocial',
        ),
    ]
