# Generated by Django 2.1 on 2018-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_building_sourcename'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sourceUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Source url'),
        ),
        migrations.AlterField(
            model_name='building',
            name='sourceName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Source name'),
        ),
    ]
