# Generated by Django 2.1 on 2018-09-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_auto_20180904_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='permisoEdificacionDate',
            field=models.DateField(blank=True, null=True, verbose_name='Permiso edificación fecha'),
        ),
        migrations.AlterField(
            model_name='building',
            name='recepcionFinalDate',
            field=models.DateField(blank=True, null=True, verbose_name='Recepcion final fecha'),
        ),
    ]
