# Generated by Django 2.1 on 2018-12-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0010_auto_20181212_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre')),
                ('complementary', models.BooleanField(blank=True, default=False, verbose_name='Complementaria')),
                ('material', models.CharField(blank=True, choices=[('-', 'Desconocido'), ('A', 'Acero'), ('B', 'Hormigón'), ('C', 'Albañilería'), ('D', 'Piedra/Bloque'), ('E', 'Madera'), ('F', 'Adobe'), ('G', 'Metalcom'), ('H', 'Prefab. Madera'), ('I', 'Prefab. Hormigón'), ('J', 'Otros')], default='-', max_length=2)),
                ('year', models.DateField(blank=True, default='1985-01-01', verbose_name='Año construcción')),
                ('quality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calidad')),
                ('state', models.IntegerField(blank=True, choices=[(1, 'Sin valor'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Muy bueno')], null=True, verbose_name='Estado')),
                ('rol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol')),
                ('prenda', models.BooleanField(blank=True, choices=[(None, 'S/A'), (True, 'Si'), (False, 'No')], null=True, verbose_name='Mercado objetivo')),
                ('recepcion', models.IntegerField(blank=True, choices=[(0, 'Con R/F'), (1, 'Sin R/F'), (2, 'Sin P/E'), (3, 'Sin Ant.'), (4, 'N/R')], default=4)),
                ('area', models.FloatField(blank=True, default=0, verbose_name='Area')),
                ('UFPerArea', models.FloatField(blank=True, default=0, verbose_name='Area')),
            ],
        ),
    ]
