# Generated by Django 2.1 on 2018-12-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='acogidaLey',
            field=models.IntegerField(blank=True, choices=[(0, 'O.G.U. y C.'), (1, 'P.R.C.'), (2, 'Ley Pereira'), (3, 'Ley 19583'), (4, 'Ley 19667'), (5, 'Ley 19727'), (6, 'Ley 20251'), (7, 'Ley 6071'), (8, 'Ninguna'), (9, 'Antigüedad')], null=True, verbose_name='Acogida a'),
        ),
        migrations.AddField(
            model_name='building',
            name='adobe',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Adobe'),
        ),
        migrations.AddField(
            model_name='building',
            name='anoConstruccion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año construcción'),
        ),
        migrations.AddField(
            model_name='building',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Antiguedad'),
        ),
        migrations.AddField(
            model_name='building',
            name='avaluoFiscal',
            field=models.FloatField(blank=True, null=True, verbose_name='Avaluo fiscal'),
        ),
        migrations.AddField(
            model_name='building',
            name='copropiedadInmobiliaria',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Copropiedad Inmobiliaria'),
        ),
        migrations.AddField(
            model_name='building',
            name='desmontable',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Desmontable'),
        ),
        migrations.AddField(
            model_name='building',
            name='destinoSII',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud'), ('SE', 'Sitio Eriazo')], max_length=1, null=True, verbose_name='Destino según SII'),
        ),
        migrations.AddField(
            model_name='building',
            name='dfl2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='DFL 2'),
        ),
        migrations.AddField(
            model_name='building',
            name='estructuraTerminaciones',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Estructura y terminaciones'),
        ),
        migrations.AddField(
            model_name='building',
            name='expropiacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Expropiacion'),
        ),
        migrations.AddField(
            model_name='building',
            name='mercadoObjetivo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Mercado objetivo'),
        ),
        migrations.AddField(
            model_name='building',
            name='ocupante',
            field=models.CharField(blank=True, choices=[('P', 'Propietario'), ('A', 'Arrendatario'), ('O', 'Otro'), ('SO', 'Sin ocupante')], max_length=2, null=True, verbose_name='Ocupante'),
        ),
        migrations.AddField(
            model_name='building',
            name='permisoEdificacionFecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha permiso edificación'),
        ),
        migrations.AddField(
            model_name='building',
            name='permisoEdificacionNo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Permiso edificación'),
        ),
        migrations.AddField(
            model_name='building',
            name='permisoEdificacionSuperficie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie permiso edificación'),
        ),
        migrations.AddField(
            model_name='building',
            name='programa',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='building',
            name='recepcionFinalFecha',
            field=models.DateField(blank=True, null=True, verbose_name='Recepcion final fecha'),
        ),
        migrations.AddField(
            model_name='building',
            name='recepcionFinalNo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Recepcion final'),
        ),
        migrations.AddField(
            model_name='building',
            name='selloVerde',
            field=models.CharField(blank=True, choices=[('V', 'Verde'), ('A', 'Amarillo'), ('R', 'Rojo'), ('NA', 'No Aplica'), ('VV', 'Verde vencido'), ('SA', 'Sin antecedentes')], max_length=2, null=True, verbose_name='Sello verde'),
        ),
        migrations.AddField(
            model_name='building',
            name='tipoBien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de bien'),
        ),
        migrations.AddField(
            model_name='building',
            name='tipoPropiedad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Usada'), (1, 'Nueva')], default=0, null=True, verbose_name='Tipo de propiedad'),
        ),
        migrations.AddField(
            model_name='building',
            name='usoActual',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud'), ('SE', 'Sitio Eriazo')], max_length=1, null=True, verbose_name='Uso actual'),
        ),
        migrations.AddField(
            model_name='building',
            name='usoFuturo',
            field=models.CharField(blank=True, choices=[('H', 'Habitacional'), ('O', 'Oficina'), ('C', 'Comercio'), ('I', 'Industria'), ('L', 'Bodega'), ('Z', 'Estacionamiento'), ('D', 'Deportes y Recreación'), ('E', 'Educación y Cultura'), ('G', 'Hotel, Motel'), ('P', 'Administración pública'), ('Q', 'Culto'), ('S', 'Salud'), ('SE', 'Sitio Eriazo')], max_length=1, null=True, verbose_name='Uso futuro'),
        ),
        migrations.AddField(
            model_name='building',
            name='vidaUtil',
            field=models.PositiveSmallIntegerField(default=80, null=True, verbose_name='Vida util'),
        ),
        migrations.AddField(
            model_name='building',
            name='vidaUtilRemanente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida util remanente'),
        ),
        migrations.AddField(
            model_name='building',
            name='viviendaSocial',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'S/A'), (2, 'Si'), (3, 'No')], default=1, verbose_name='Vivienda social'),
        ),
    ]
