# Generated by Django 2.1 on 2018-12-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_auto_20181213_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='marketPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado UF'),
        ),
        migrations.AddField(
            model_name='building',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (2, 'Departamento'), (3, 'Edificio'), (4, 'Condominio'), (0, 'Otro')], default=0),
        ),
    ]
