# Generated by Django 2.1 on 2018-09-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_building_propertytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='lon',
            new_name='lng',
        ),
    ]
