# Generated by Django 2.1 on 2018-12-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0048_realestate_buildings'),
        ('building', '0013_auto_20181213_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='real_estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.RealEstate', verbose_name='Real estate'),
        ),
    ]
