# Generated by Django 2.1 on 2018-09-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0014_auto_20180925_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='adobe',
        ),
        migrations.RemoveField(
            model_name='building',
            name='desmontable',
        ),
    ]
