# Generated by Django 2.1 on 2018-12-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0014_building_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.RealEstate', verbose_name='Real estate'),
        ),
    ]
