# Generated by Django 2.1 on 2018-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_auto_20181218_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (1, 'Casa'), (2, 'Departamento'), (6, 'Oficina'), (7, 'Local Comercial'), (8, 'Terreno'), (9, 'Industria'), (10, 'Galpon'), (11, 'Bodega'), (12, 'Estacionamiento'), (3, 'Edificio'), (13, 'Parcela'), (14, 'Barco'), (15, 'Vehiculo'), (16, 'Maquinaria'), (17, 'Estación de Servicio'), (18, 'Condominio'), (0, 'Otro')], default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='selloVerde',
            field=models.CharField(blank=True, choices=[('V', 'Verde'), ('A', 'Amarillo'), ('AV', 'Amarillo Vencido'), ('R', 'Rojo'), ('NA', 'No Aplica'), ('VV', 'Verde vencido'), ('SA', 'Sin antecedentes')], max_length=2, null=True, verbose_name='Sello verde'),
        ),
    ]
