# Generated by Django 2.1 on 2018-12-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0016_auto_20181219_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='estructuraTerminaciones',
        ),
        migrations.RemoveField(
            model_name='building',
            name='programa',
        ),
    ]
