# Generated by Django 2.1 on 2018-12-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0017_auto_20181220_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='tipoPropiedad',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Usada'), (1, 'Nueva'), (3, 'No Aplica')], default=0, null=True, verbose_name='Tipo de propiedad'),
        ),
    ]
