# Generated by Django 2.1 on 2018-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0018_auto_20181227_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='propertyType',
            field=models.PositiveIntegerField(choices=[('', '---------'), (8, 'Terreno'), (1, 'Casa'), (3, 'Edificio'), (2, 'Departamento'), (6, 'Oficina'), (7, 'Local Comercial'), (9, 'Industria'), (10, 'Galpon'), (11, 'Bodega'), (12, 'Estacionamiento'), (13, 'Parcela'), (14, 'Barco'), (15, 'Vehiculo'), (16, 'Maquinaria'), (17, 'Estación de Servicio'), (18, 'Condominio'), (0, 'Otro')], default=0),
        ),
    ]
