# Generated by Django 2.1 on 2018-09-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='timeDue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time due'),
        ),
    ]
