# Generated by Django 2.1 on 2018-09-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_auto_20180924_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='timeDue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time due'),
        ),
    ]
