# Generated by Django 2.1 on 2019-01-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressNumber2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dpto.')),
                ('marketPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado')),
                ('fromApartment', models.BooleanField(default=False, verbose_name='Creado desde departamento')),
                ('generalDescription', models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general')),
                ('builtSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Superficie construida')),
                ('building', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Building', verbose_name='Edificio')),
                ('similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartmentbuilding.ApartmentBuilding')),
            ],
        ),
    ]
