# Generated by Django 2.1 on 2019-01-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuilding',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
    ]
