# Generated by Django 2.1 on 2018-12-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentbuilding',
            old_name='hola',
            new_name='fromApartment',
        ),
    ]
