# Generated by Django 2.1 on 2018-12-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_auto_20181213_2018'),
        ('apartmentbuilding', '0002_auto_20181212_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuilding',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Building', verbose_name='Edificio'),
        ),
    ]
