# Generated by Django 2.1 on 2019-01-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0002_apartmentbuilding_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentbuilding',
            old_name='floor',
            new_name='floors',
        ),
    ]
