# Generated by Django 2.1 on 2019-01-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0003_auto_20190109_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pisos'),
        ),
    ]
