# Generated by Django 2.1 on 2018-12-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0003_apartmentbuilding_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='building',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Building', verbose_name='Edificio'),
        ),
    ]
