# Generated by Django 2.1 on 2018-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0004_auto_20181219_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuilding',
            name='marketPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado'),
        ),
    ]
