# Generated by Django 2.1 on 2018-12-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentbuilding', '0007_apartmentbuilding_builtsquaremeters'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuilding',
            name='generalDescription',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
    ]
