# Generated by Django 2.1 on 2019-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_remove_condominium_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominium',
            name='ctype',
            field=models.PositiveIntegerField(choices=[(1, 'Condominio'), (2, 'Población'), (3, 'Sector'), (4, 'Villa'), (5, 'Cerro'), (6, 'Conjunto Habitacional'), (0, 'Otro')], default=0),
        ),
    ]
