# Generated by Django 2.1 on 2018-12-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre')),
                ('frente', models.FloatField(blank=True, null=True, verbose_name='Frente')),
                ('fondo', models.FloatField(blank=True, null=True, verbose_name='Fondo')),
                ('topography', models.IntegerField(blank=True, choices=[(0, 'Plano'), (1, 'Semiplano'), (2, 'Pendiente'), (3, 'Pendiente abrupta')], null=True, verbose_name='Topografía')),
                ('shape', models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Irregular')], null=True, verbose_name='Forma')),
                ('area', models.FloatField(blank=True, default=0, verbose_name='Area')),
                ('rol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol')),
                ('uf_per_area', models.FloatField(blank=True, default=0, verbose_name='UF per Area')),
            ],
        ),
    ]
