# Generated by Django 2.1 on 2019-01-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre')),
                ('addressNumber2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dpto.')),
                ('frente', models.FloatField(blank=True, null=True, verbose_name='Frente')),
                ('fondo', models.FloatField(blank=True, null=True, verbose_name='Fondo')),
                ('topography', models.IntegerField(blank=True, choices=[(0, 'Plano'), (1, 'Semiplano'), (2, 'Pendiente'), (3, 'Pendiente abrupta')], null=True, verbose_name='Topografía')),
                ('shape', models.IntegerField(blank=True, choices=[(0, 'Regular'), (1, 'Irregular')], null=True, verbose_name='Forma')),
                ('area', models.FloatField(blank=True, default=0, verbose_name='Area')),
                ('uf_per_area', models.FloatField(blank=True, default=0, verbose_name='UF per Area')),
                ('marketPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mercado')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.RealEstate', verbose_name='Real estate')),
                ('similar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terrain.Terrain')),
            ],
        ),
    ]
