# Generated by Django 2.1 on 2019-01-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='addressNumber2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Lote'),
        ),
    ]
