# Generated by Django 2.1 on 2018-12-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0002_terrain_marketprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='rol',
        ),
    ]
