# Generated by Django 2.1 on 2019-01-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0003_auto_20190106_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='generalDescription',
            field=models.TextField(blank=True, default='', max_length=10000, null=True, verbose_name='Descripcion general'),
        ),
    ]
