# Generated by Django 2.1 on 2018-12-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0051_auto_20181219_1847'),
        ('terrain', '0004_terrain_addressnumber2'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='real_estate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='realestate.RealEstate', verbose_name='Real estate'),
            preserve_default=False,
        ),
    ]
