# Generated by Django 2.1 on 2019-01-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0005_terrain_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='similar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terrain.Terrain'),
        ),
    ]
