# Generated by Django 2.1.1 on 2018-10-11 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0004_auto_20180824_1229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commune', '0002_auto_20180824_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.CharField(default=0, max_length=10, verbose_name='Numero')),
                ('addressCommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna')),
                ('addressRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
