# Generated by Django 2.1 on 2019-05-13 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commune', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(default='', max_length=100)),
                ('appraisal_id', models.IntegerField(null=True)),
                ('comment_id', models.IntegerField(null=True)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='Time created')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('rut', models.CharField(max_length=14, null=True, verbose_name='RUT')),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.CharField(max_length=10, verbose_name='Numero')),
                ('addressCommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna')),
                ('addressRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region')),
                ('notifications', models.ManyToManyField(to='user.Notification')),
            ],
            options={
                'permissions': (('view_accounting', 'Can view accounting'), ('evaluate_tasador', 'Can evaluate appraisers')),
            },
        ),
    ]
