# Generated by Django 2.1 on 2018-11-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('rut', models.CharField(max_length=14, null=True, verbose_name='RUT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('addressStreet', models.CharField(default='', max_length=300, verbose_name='Calle')),
                ('addressNumber', models.CharField(max_length=10, verbose_name='Numero')),
                ('addressCommune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune.Commune', to_field='code', verbose_name='Comuna')),
                ('addressRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', to_field='code', verbose_name='Region')),
            ],
        ),
    ]
