# Generated by Django 2.1.1 on 2018-10-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181018_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='addressNumber',
            field=models.CharField(max_length=10, verbose_name='Numero'),
        ),
    ]
