# Generated by Django 2.1 on 2019-03-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190123_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_accounting', 'Can view accounting'),)},
        ),
    ]
