# Generated by Django 2.1.1 on 2018-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181030_1701'),
    ]

    operations = [
    ]
